name: MacOS + Upstream Bzip2 1.0

on: [push, pull_request]

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        perl:
          - '5.36'
          # - '5.34'
          # - '5.32'
          # - '5.30'
          # - '5.28'
          # - '5.26'
          # - '5.24'
          # - '5.22'
          # - '5.20'
          # - '5.18'
          # - '5.16'
          # - '5.14'
          # - '5.12'
          # - '5.10'
          # - '5.8'
          # - '5.6'
        bzip2-version:
          - master

    name: Perl ${{ matrix.perl }} + Upstream '${{ matrix.bzip2-version }}'
    steps:
    - uses: actions/checkout@v1

    - name: Set Env
      run: |
        echo "bzip2-source=${GITHUB_WORKSPACE}/upstream-bzip2-source-${{ matrix.bzip2-version }}" >> $GITHUB_ENV
        echo "bzip2-install=${HOME}/upstream-bzip2-install-${{ matrix.bzip2-version }}"           >> $GITHUB_ENV
        echo "BZIP2_LIB=${HOME}/upstream-bzip2-install-${{ matrix.bzip2-version }}"               >> $GITHUB_ENV
        echo "BZIP2_INCLUDE=${HOME}/upstream-bzip2-install-${{ matrix.bzip2-version }}"           >> $GITHUB_ENV
        # echo "BZIP2_VERSION=${{ matrix.bzip2-version }}"                                        >> $GITHUB_ENV
        echo "BZIP2_VERSION=1.0.999"                                                              >> $GITHUB_ENV
        echo "BUILD_BZIP2=0"                                                                      >> $GITHUB_ENV

    - name: Checkout upstream bzip2 '${{matrix.bzip2-version}}''
      run: |
        mkdir -p ${{ env.bzip2-source }}
        cd ${{ env.bzip2-source }}
        git clone https://sourceware.org/git/bzip2.git .
        sed -i -e s'/BZ_VERSION  "1.0.8.*"/BZ_VERSION "${{ env.BZIP2_VERSION }}"/' bzlib_private.h

    # mac makefile sourced from https://stackoverflow.com/questions/67179779/building-and-installing-bzip2-with-shared-library-dylib-on-macos
    - name: Build upstream bzip2 '${{matrix.bzip2-version}}''
      run: |
        #wget -c https://gist.githubusercontent.com/obihill/3278c17bcee41c0c8b59a41ada8c0d35/raw/3bf890e2ad40d0af358e153395c228326f0b44d5/Makefile-libbz2_dylib
        #make -f Makefile-libbz2_dylib
        gcc --shared -Wl,-install_name -Wl,libbz2.dylib -fpic -fPIC -Wall -Winline -O2 -g -D_FILE_OFFSET_BITS=64  blocksort.c huffman.c crctable.c randtable.c compress.c decompress.c bzlib.c  -o libbz2.${{ env.BZIP2_VERSION }}.dylib
        ln -s libbz2.${{ env.BZIP2_VERSION }}.dylib libbz2.dylib
        mkdir -p ${{ env.bzip2-install }}
        cp bzlib.h libbz2.${{ env.BZIP2_VERSION }}.dylib libbz2.dylib ${{ env.bzip2-install }}
        # make clean
        rm  libbz2.${{ env.BZIP2_VERSION }}.dylib libbz2.dylib
      working-directory: ${{ env.bzip2-source }}

    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: Perl version
      run: perl -V

    - name: Install dependencies
      run: cpanm --quiet --installdeps --notest .

    - name: Build
      run: perl Makefile.PL && make

    - name: Test
      run: make test

    - name:  Bzip2 Version
      run: perl -Mblib -MCompress::Raw::Bzip2 -e 'print Compress::Raw::Bzip2::bzlibversion(). "\n"'