name: MacOS + Upstream GitLab Bzip2 1.1

on:
  workflow_dispatch:
  push:
  pull_request:
  schedule:
      - cron: '02 02 * * 6'    # Run every Saturday

jobs:
  build:

    runs-on: macos-latest

    strategy:
      matrix:
        perl:
          - '5.38'
          # - '5.36'
          # - '5.34'
          # - '5.32'
          # - '5.30'
          # - '5.28'
          # - '5.26'
          # - '5.24'
          # - '5.22'
          # - '5.20'
          # - '5.18'
          # - '5.16'
          # - '5.14'
          # - '5.12'
          # - '5.10'
          # - '5.8'
          # - '5.6'
        bzip2-version:
          - master
        dummy-version:
          - '1.0.999'

    env:
      bzip2-source:      ${{ github.workspace }}/upstream-bzip2-source
      bzip2-install:     ${{ github.workspace }}/upstream-bzip2-install
      BZIP2_LIB:         ${{ github.workspace }}/upstream-bzip2-install/lib
      BZIP2_INCLUDE:     ${{ github.workspace }}/upstream-bzip2-install/include
      BZIP2_VERSION:     ${{ matrix.bzip2-version }}
      BUILD_BZIP2:       0

    defaults:
      run:
        working-directory: repo

    name: Perl ${{ matrix.perl }} + Upstream GitLab '${{ matrix.bzip2-version }}'
    steps:

    - uses: actions/checkout@v3
      with:
        path: repo

    - name: Make Paths
      run: |
        mkdir -p ${{ env.bzip2-source }}
        mkdir -p ${{ env.bzip2-install }}
        mkdir -p ${{ github.workspace }}/repo

    - name: Checkout upstream bzip2 '${{matrix.bzip2-version}}'
      run: |
        git clone https://gitlab.com/bzip2/bzip2.git .
        sed -i -e s'/BZ_VERSION  "1.0.8.*"/BZ_VERSION "${{ env.BZIP2_VERSION }}"/' bzlib_private.h
      working-directory: ${{ env.bzip2-source }}

    - name: Build upstream bzip2 '${{matrix.bzip2-version}}''
      run: |
        mkdir build
        cd build
        cmake ..
        make DESTDIR=${{ env.bzip2-install }} install
        make clean
      working-directory: ${{ env.bzip2-source }}

    - name: Setup perl
      uses: shogo82148/actions-setup-perl@v1
      with:
        perl-version: ${{ matrix.perl }}

    - name: Perl version
      run: perl -V

    # - name: Install dependencies
    #   run: cpanm --quiet --installdeps --notest .

    - name: Build
      run: perl Makefile.PL && make

    - name: Test
      run: make test

    - name: Bzip2 Version
      run: perl -Mblib -MCompress::Raw::Bzip2 -e 'print Compress::Raw::Bzip2::bzlibversion(). "\n"'